export default {
    'login': 'HariBhandari07',
    'id': 34328907,
    'node_id': 'MDQ6VXNlcjM0MzI4OTA3',
    'avatar_url': 'https://avatars1.githubusercontent.com/u/34328907?v=4',
    'gravatar_id': '',
    'url': 'https://api.github.com/users/HariBhandari07',
    'html_url': 'https://github.com/HariBhandari07',
    'followers_url': 'https://api.github.com/users/HariBhandari07/followers',
    'following_url': 'https://api.github.com/users/HariBhandari07/following{/other_user}',
    'gists_url': 'https://api.github.com/users/HariBhandari07/gists{/gist_id}',
    'starred_url': 'https://api.github.com/users/HariBhandari07/starred{/owner}{/repo}',
    'subscriptions_url': 'https://api.github.com/users/HariBhandari07/subscriptions',
    'organizations_url': 'https://api.github.com/users/HariBhandari07/orgs',
    'repos_url': 'https://api.github.com/users/HariBhandari07/repos',
    'events_url': 'https://api.github.com/users/HariBhandari07/events{/privacy}',
    'received_events_url': 'https://api.github.com/users/HariBhandari07/received_events',
    'type': 'User',
    'site_admin': false,
    'name': 'Hari Bhandari',
    'company': null,
    'blog': '',
    'location': null,
    'email': null,
    'hireable': true,
    'bio': 'get busy living or get busy dying',
    'twitter_username': null,
    'public_repos': 9,
    'public_gists': 0,
    'followers': 6,
    'following': 19,
    'created_at': '2017-12-07T04:33:28Z',
    'updated_at': '2020-08-23T02:22:18Z'
}
